print("hello world")
for i in range(5):
  print ("apple")
  print ("banana")
  print("cup")
  print("doll")
  print("egg")
  print("fish")
  print("gold")
  print("hello")
  print("ice")
  print("july")
  print("kate")
  print("lemon")
